version: 0.0
os: linux
files:
  - source: /
    destination: /writeItDown
hooks:
  ApplicationStop:
    - location: deploy/stop_app.sh
      timeout: 20
  AfterInstall:
    - location: deploy/get_cert.sh
      timeout: 60
  ApplicationStart:
    - location: deploy/start_app.sh
      timeout: 20